# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-US"
title                    : "Frame by Frame"
title_separator          : "-"
description              : "SILENT COMICS log."
words_per_minute         : 200
github_username          : SilentComics
repository               : "frame-by-frame"
baseurl                  : "" # the subpath of your site, e.g. /blog
url                      : "https://log.silentcomics.com"

environment: production

# Staticman comments (full configuration in staticman.yml)
staticman:
  branch: "master"


feed:

# Social Sharing
twitter:
  username               : SilentComics
github:
  username               : SilentComics
tumblr:
  username               : silent-comics
facebook:
  username               : SilentComics
  app_id                 :
  publisher              :
  admins                 :
og_image                 : "/images/index_silent-comics.png" # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  name                   : SilentComics
  links:
    - "https://twitter.com/SilentComics/"
    - "https://facebook.com/SilentComics/"
    - "https://github.com/SilentComics/"
    - "https://silent-comics.tumblr.com/"
    - "https://www.instagram.com/silent_comics/"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - vendor
  - vendor/cache
  - .asset-cache
  - .bundle
  - .git
  - .jekyll-cache
  - .jekyll-assets-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - CHANGELOG
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - log
  - node_modules
  - package-lock.json
  - package.json
  - Rakefile.rb
  - README
  - tmp
  - config.codekit3

keep_files:
  - .git
  - images
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Jekyll configuration
#permalink                : /:categories/:title/
# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  essays:
    output: true
    permalink: /:collection/:path/
  music:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _essays
  - scope:
      path: ""
      type: essays
    values:
      layout: single
      author_profile: true
      read_time: true
  # _comics
  - scope:
      path: ""
      type: comics
    values:
      layout: comic
      author_profile: false

# Outputting
# Plugin: Pagination (jekyll-paginate-v2)
pagination:
  enabled: True
  collection: posts
  per_page: 10
  permalink: "/page:num/"
  title: ":title"
  limit: 0
  sort_field: "date"
  sort_reverse: true
  trail:
    before: 2
    after: 2

# Produces a cleaner folder structure when using categories
permalink:  /:categories/:title/

# Plugin: Auto Pages (jekyll-paginate-v2)
autopages:
  enabled: true
  categories:
    enabled: true
    layouts:
      - "autopage_categories.html"
    permalink: '/category/:cat'
  collections:
    enabled: false
  tags:
    enabled: true
    slugify:
      mode: raw
      cased: true
    layouts:
      - "autopage_tags.html"
    title: ":tag" # :tag is replaced by the tag name
    permalink: '/tag/:tag'

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-image-size
  - jekyll-redirect-from

  # Jekyll Picture Tag general settings
picture:
  source: "images/"
  output: "images/" # images/resized/%{width}/%{basename}
  relative_url: true #(true|false)
  nomarkdown: true # true or false

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
