  [build]
    command = "jekyll build"
    publish = "_site"

  [build.environment]
    JEKYLL_ENV = "production"

  [staticman]
        api = "https://api.staticman.net/v3/entry/github/SilentComics/silentcomics/master/comments"
        pulls = "https://github.com/SilentComics/silentcomics/pulls"
